### ISSUE TITLE
RZ/V2L: Support for IPC between A55 and M33 processors

### ISSUE THREAD

**Issue by ricoheller** [renesas-rz/meta-renesas#10]
Hi, 

I wish to run a RT application in the M33 core while the other A55 cores run the Yocto based Linux.
Can I achieve that using meta-renesas and meta-openamp?

Thanks!

**Comment by seebe** [comment]
There is an App Note and sample code on that.
https://www.renesas.com/us/en/software-tool/rzv2l-group-multi-os-package
