### ISSUE TITLE
fetcher failure glib-2.0-native-2.58.3-r0 

### ISSUE THREAD

**Issue by Anzal-calixto** [renesas-rz/meta-renesas#11]
my build is being failed due to this fetch error the vlp i am using 3.0.3 i am trying to build weston image.

**Comment by seebe** [comment]
Debian removed a file from their server. So a different filename needs to be downloaded. The recipe has been updated.

https://github.com/renesas-rz/meta-renesas/blob/dunfell/rz/meta-rz-common/recipes-debian/buster/sources/glib2.0.inc

Commit: https://github.com/renesas-rz/meta-renesas/commit/5377babf0f79b1a6a434503c5d083e5b047da47d

**Comment by Anzal-calixto** [comment]
okay thanks should i add the same file to my cloned layer or which brach should i checkout. Also i am installing grphic liobrary and video codec to the recipe does changing to 'dunfell/rz' confict with the above

**Comment by seebe** [comment]
This is on the "dunfell/rz" branch. The same branch that BSP v3.0.3 was taken from.

If you look in the commit history, you can see the different versions.

https://github.com/renesas-rz/meta-renesas/commits/dunfell/rz/

"Bump into version BSP-3.0.6"
"Bump into version BSP-3.0.5"
"Bump into version BSP-3.0.4"
"Bump into version BSP-3.0.3"

**Comment by Anzal-calixto** [comment]
okay thankyou
