### ISSUE TITLE
glibc_2.28-10+deb10u2 is no longer availble

### ISSUE THREAD

**Issue by tim-carney-cargt** [renesas-rz/meta-renesas#12]
Should the glibc version be upgraded to 10u3?

It appears that 10u2 is no longer available and results in a failure to fetch:

WARNING: glibc-2.28-r0 do_fetch: Failed to fetch URL https://security.debian.org/debian-security/pool/updates/main/g/glibc/glibc_2.28-10+deb10u2.debian.tar.xz;name=glibc_2.28-10+deb10u2.debian.tar.xz,

This error occurs while trying to build core-image-minimal for smarc-rzg3s.

**Comment by seebe** [comment]
Yes, we will changing to use 10u3 for the next release.
