### ISSUE TITLE
Build can no longer fetch rz_linux-clip

### ISSUE THREAD

**Issue by Eldex-Mark** [renesas-rz/meta-renesas#13]
While running linux-libc-headders_5.10.bb & linux-renesas_5.10.bb can't fetch error when trying to build.
MACHINE=smarc-rzg2l bitbake core-image-bsp

**Comment by patersonc** [comment]
Hello @Eldex-Mark 

What version of meta-renesas are you trying to build?

Do you have any logs of the fetch failure?

Thanks

**Comment by Eldex-Mark** [comment]
Hi - I was trying to do this in a Docker window - Finally gave up on it and build a new computer out of old parts with a new load of Ubuntu 20.04. Everything worked as it should after applying the Renesas patches to the libc-headders-5.10 recipe. This relates to what Renesas calls the "update3" version of recipes on their website. Probably something I was doing wrong.
