### ISSUE TITLE
Khronos headers compile error

### ISSUE THREAD

**Issue by milad6506** [renesas-rz/meta-renesas#3]
Hi 
I hope it is the right place to issue thid
The khronos-header fails on do_fetch due to checksum mismatch and when i manually fixed it, it failed on patch.
This error occurred while building a weston image for stout on ubuntu 14.

**Comment by renesas-rz** [comment]
Hi,
The meta-renesas Yocto layer is for Renesas RZ (RZ/G) devices and boards, and stout is an R-Car board. You should use the instructions and build layers here - http://elinux.org/R-Car/Boards/Stout, for building BSPs for the stout board.
