### ISSUE TITLE
build fails fetch openssl_1.1.1n-0+deb10u3.dsc

### ISSUE THREAD

**Issue by greku** [renesas-rz/meta-renesas#8]
Hello,

Build currently fails due to fetch error of file openssl_1.1.1n-0+deb10u3.dsc referenced in 
recipes-common/recipes-debian/buster/sources/openssl.inc
on tag BSP-3.0.2-update1
I suppose file needs to be updated to openssl_1.1.1n-0+deb10u4.dsc

**Comment by tdhung** [comment]
Hello @greku,

Thank you for the issue report.
Now this issue has been fixed (in latest version BSP-3.0.3)

**Comment by marklinmax** [comment]
Now same error with openssl_1.1.1n-0+deb10u5.dsc. Minimal version available at the target url is now openssl_1.1.1n-0+deb10u6.dsc
Maybe using another way than the full URL to get the latest package version would prevent those errors each time the old package is removed from the targeted repository...
By the way, I am using the VLP v3.0.4 from the Renesas website, which is at this time the latest.

**Comment by tdhung** [comment]
Hi @marklinmax,
Thank you for your comment.
We have pushed update for opnessl on branch dunfell/rz. Please use it if you need.
