### ISSUE TITLE
kirkstone support

### ISSUE THREAD

**Issue by ricoheller** [renesas-rz/meta-renesas#9]
Hello, 

Do you have any plans to support the current Yocto LTS (Kirkstone) in the near future?

Thanks

**Comment by seebe** [comment]
We are investigating it now. There are some recipe syntax changes needed for Dunfell->Kirkstone.

The current idea is to post a more simple Kirkstone meta-renesas layer for users to use as refence while the official BSP remains Dunfell.

**Comment by trisbs** [comment]
Is there any milestone to release for supporting Kirkstone now?
Thank you.

**Comment by seebe** [comment]
We do not have a release date yet. We are still in the process of porting over the current Dunfell recipes.

**Comment by hyyoxhk** [comment]
I think this bsp layer is too difficult to use, why not refer to meta-freescale or meta-st-stm32mp.
If you plan to support Kirkstone, please be sure to align it with the yocto community.

Feedback and complaints from your customers.

**Comment by hyyoxhk** [comment]
> We are investigating it now. There are some recipe syntax changes needed for Dunfell->Kirkstone.
> 
> The current idea is to post a more simple Kirkstone meta-renesas layer for users to use as refence while the official BSP remains Dunfell.

You can use the [convert-overrides.py](https://git.yoctoproject.org/poky/tree/scripts/contrib/convert-overrides.py) to convert to new syntax

**Comment by trisbs** [comment]
According to [VLP_support_version_overview](https://renesas.info/w/images/2/2c/VLP_support_version_overview.png), seems that Dunfell will be kept till a migration to Scarthgap (after 2025)?

**Comment by seebe** [comment]
> According to [VLP_support_version_overview](https://renesas.info/w/images/2/2c/VLP_support_version_overview.png), seems that Dunfell will be kept till a migration to Scarthgap (after 2025)?

Yes, that is correct.

There is a Kirkstone based Yocto build here: https://github.com/renesas-rz/rz-community-bsp
However, it is not an official release and some features are missing.
